version: "3.9"
services:
  mongo:
    image: mongo
    network_mode: host
    ports:
    - "27017:27017"
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    network_mode: host
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka:5.5.0
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7981:7981"
    network_mode: host
    depends_on:
      - mongo
      - kafka

volumes:
  pg_data: