name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: bitnami/mongodb:4.2
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: generate
      run: make generate
    - name: build
      run: make build
    - name: update permissions
      run: |
        ls -l ./
        chmod +x /bin/app
    - name: run
      run:  ./bin/app
    - name: Test
      run: make test
